/*
 * generated by Xtext 2.13.0
 */
package de.itemis.sakop


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class InfoModelDSLStandaloneSetup extends InfoModelDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new InfoModelDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
