/*
 * generated by Xtext 2.13.0
 */
package de.itemis.sakop.ide


/**
 * Use this class to register ide components.
 */
class InfoModelDSLIdeModule extends AbstractInfoModelDSLIdeModule {
}
