/*
 * generated by Xtext 2.13.0
 */
package de.itemis.sakop.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class InfoModelDSLUiModule extends AbstractInfoModelDSLUiModule {
}
